### ISSUE TITLE
Trainer class use fails with the error  "No module named 'torchvision.models.utils'"

### ISSUE THREAD

**Issue by shubham166** [median-research-group/LibMTL#21] opened 2022-11-19 08:04 UTC
Trainer class use fails with the error  "No module named 'torchvision.models.utils'"

Full stack here - 
Traceback (most recent call last):
  File "src/main/pipelines/train_nsfw_mtl.py", line 11, in <module>
    from LibMTL import Trainer
  File "/azureml-envs/azureml_8a26314e09753d45d0790003a01faf79/lib/python3.8/site-packages/LibMTL/__init__.py", line 2, in <module>
    from . import model
  File "/azureml-envs/azureml_8a26314e09753d45d0790003a01faf79/lib/python3.8/site-packages/LibMTL/model/__init__.py", line 1, in <module>
    from LibMTL.model.resnet import resnet18
  File "/azureml-envs/azureml_8a26314e09753d45d0790003a01faf79/lib/python3.8/site-packages/LibMTL/model/resnet.py", line 3, in <module>
    from torchvision.models.utils import load_state_dict_from_url
ModuleNotFoundError: No module named 'torchvision.models.utils'

The issue is fixed by using 'torch.hub' instead.

**Comment by Baijiong-Lin** [comment] 2022-11-19 08:42
I guess this problem is caused by the different versions of torchvision. We use version 0.9.0 here. We have clearly clarified the required packages with their corresponding version in [LibMTL v1.1.6](https://github.com/median-research-group/LibMTL/tree/v1.1.6) which will be released formally soon.

**Comment by Baijiong-Lin** [comment] 2022-11-26 07:25
Closed as no further updates.

**Closed by Baijiong-Lin** 2022-11-26 07:25 UTC
